import collections

from handlers import (
    Implicit, DirectXIndirect, Illegal, Direct, Immediate, Accumulator,
    Absolute, Relative, DirectIndirectY, DirectX, AbsoluteY, AbsoluteX,
    Ret, JmpAbsolute, JmpAbsoluteIndirect, DirectY)


InstrDesc = collections.namedtuple("InstrDesc",
    ["mnemonic", "size", "handler_class"])


opcode_table = [
    InstrDesc("BRK", 1, Implicit), # 0x00
    InstrDesc("ORA", 2, DirectXIndirect), # 0x01
    InstrDesc("???", 1, Illegal), # 0x02
    InstrDesc("???", 1, Illegal), # 0x03
    InstrDesc("???", 1, Illegal), # 0x04
    InstrDesc("ORA", 2, Direct), # 0x05
    InstrDesc("ASL", 2, Direct), # 0x06
    InstrDesc("???", 1, Illegal), # 0x07
    InstrDesc("PHP", 1, Implicit), # 0x08
    InstrDesc("ORA", 2, Immediate), # 0x09
    InstrDesc("ASL", 1, Accumulator), # 0x0a
    InstrDesc("???", 1, Illegal), # 0x0b
    InstrDesc("???", 1, Illegal), # 0x0c
    InstrDesc("ORA", 3, Absolute), # 0x0d
    InstrDesc("ASL", 3, Absolute), # 0x0e
    InstrDesc("???", 1, Illegal), # 0x0f
    InstrDesc("BPL", 2, Relative), # 0x10
    InstrDesc("ORA", 2, DirectIndirectY), # 0x11
    InstrDesc("???", 1, Illegal), # 0x12
    InstrDesc("???", 1, Illegal), # 0x13
    InstrDesc("???", 1, Illegal), # 0x14
    InstrDesc("ORA", 2, DirectX), # 0x15
    InstrDesc("ASL", 2, DirectX), # 0x16
    InstrDesc("???", 1, Illegal), # 0x17
    InstrDesc("CLC", 1, Implicit), # 0x18
    InstrDesc("ORA", 3, AbsoluteY), # 0x19
    InstrDesc("???", 1, Illegal), # 0x1a
    InstrDesc("???", 1, Illegal), # 0x1b
    InstrDesc("???", 1, Illegal), # 0x1c
    InstrDesc("ORA", 3, AbsoluteX), # 0x1d
    InstrDesc("ASL", 3, AbsoluteX), # 0x1e
    InstrDesc("???", 1, Illegal), # 0x1f
    InstrDesc("JSR", 3, Absolute), # 0x20
    InstrDesc("AND", 2, DirectXIndirect), # 0x21
    InstrDesc("???", 1, Illegal), # 0x22
    InstrDesc("???", 1, Illegal), # 0x23
    InstrDesc("BIT", 2, Direct), # 0x24
    InstrDesc("AND", 2, Direct), # 0x25
    InstrDesc("ROL", 2, Direct), # 0x26
    InstrDesc("???", 1, Illegal), # 0x27
    InstrDesc("PLP", 1, Implicit), # 0x28
    InstrDesc("AND", 2, Immediate), # 0x29
    InstrDesc("ROL", 1, Accumulator), # 0x2a
    InstrDesc("???", 1, Illegal), # 0x2b
    InstrDesc("BIT", 3, Absolute), # 0x2c
    InstrDesc("AND", 3, Absolute), # 0x2d
    InstrDesc("ROL", 3, Absolute), # 0x2e
    InstrDesc("???", 1, Illegal), # 0x2f
    InstrDesc("BMI", 2, Relative), # 0x30
    InstrDesc("AND", 2, DirectIndirectY), # 0x31
    InstrDesc("???", 1, Illegal), # 0x32
    InstrDesc("???", 1, Illegal), # 0x33
    InstrDesc("???", 1, Illegal), # 0x34
    InstrDesc("AND", 2, DirectX), # 0x35
    InstrDesc("ROL", 2, DirectX), # 0x36
    InstrDesc("???", 1, Illegal), # 0x37
    InstrDesc("SEC", 1, Implicit), # 0x38
    InstrDesc("AND", 3, AbsoluteY), # 0x39
    InstrDesc("???", 1, Illegal), # 0x3a
    InstrDesc("???", 1, Illegal), # 0x3b
    InstrDesc("???", 1, Illegal), # 0x3c
    InstrDesc("AND", 3, AbsoluteX), # 0x3d
    InstrDesc("ROL", 3, AbsoluteX), # 0x3e
    InstrDesc("???", 1, Illegal), # 0x3f
    InstrDesc("RTI", 1, Ret), # 0x40
    InstrDesc("EOR", 2, DirectXIndirect), # 0x41
    InstrDesc("???", 1, Illegal), # 0x42
    InstrDesc("???", 1, Illegal), # 0x43
    InstrDesc("???", 1, Illegal), # 0x44
    InstrDesc("EOR", 2, Direct), # 0x45
    InstrDesc("LSR", 2, Direct), # 0x46
    InstrDesc("???", 1, Illegal), # 0x47
    InstrDesc("PHA", 1, Implicit), # 0x48
    InstrDesc("EOR", 2, Immediate), # 0x49
    InstrDesc("LSR", 1, Accumulator), # 0x4a
    InstrDesc("???", 1, Illegal), # 0x4b
    InstrDesc("JMP", 3, JmpAbsolute), # 0x4c
    InstrDesc("EOR", 3, Absolute), # 0x4d
    InstrDesc("LSR", 3, Absolute), # 0x4e
    InstrDesc("???", 1, Illegal), # 0x4f
    InstrDesc("BVC", 2, Relative), # 0x50
    InstrDesc("EOR", 2, DirectIndirectY), # 0x51
    InstrDesc("???", 1, Illegal), # 0x52
    InstrDesc("???", 1, Illegal), # 0x53
    InstrDesc("???", 1, Illegal), # 0x54
    InstrDesc("EOR", 2, DirectX), # 0x55
    InstrDesc("LSR", 2, DirectX), # 0x56
    InstrDesc("???", 1, Illegal), # 0x57
    InstrDesc("CLI", 1, Implicit), # 0x58
    InstrDesc("EOR", 3, AbsoluteY), # 0x59
    InstrDesc("???", 1, Illegal), # 0x5a
    InstrDesc("???", 1, Illegal), # 0x5b
    InstrDesc("???", 1, Illegal), # 0x5c
    InstrDesc("EOR", 3, AbsoluteX), # 0x5d
    InstrDesc("LSR", 3, AbsoluteX), # 0x5e
    InstrDesc("???", 1, Illegal), # 0x5f
    InstrDesc("RTS", 1, Ret), # 0x60
    InstrDesc("ADC", 2, DirectXIndirect), # 0x61
    InstrDesc("???", 1, Illegal), # 0x62
    InstrDesc("???", 1, Illegal), # 0x63
    InstrDesc("???", 1, Illegal), # 0x64
    InstrDesc("ADC", 2, Direct), # 0x65
    InstrDesc("ROR", 2, Direct), # 0x66
    InstrDesc("???", 1, Illegal), # 0x67
    InstrDesc("PLA", 1, Implicit), # 0x68
    InstrDesc("ADC", 2, Immediate), # 0x69
    InstrDesc("ROR", 1, Accumulator), # 0x6a
    InstrDesc("???", 1, Illegal), # 0x6b
    InstrDesc("JMP", 3, JmpAbsoluteIndirect), # 0x6c
    InstrDesc("ADC", 3, Absolute), # 0x6d
    InstrDesc("ROR", 3, Absolute), # 0x6e
    InstrDesc("???", 1, Illegal), # 0x6f
    InstrDesc("BVS", 2, Relative), # 0x70
    InstrDesc("ADC", 2, DirectIndirectY), # 0x71
    InstrDesc("???", 1, Illegal), # 0x72
    InstrDesc("???", 1, Illegal), # 0x73
    InstrDesc("???", 1, Illegal), # 0x74
    InstrDesc("ADC", 2, DirectX), # 0x75
    InstrDesc("ROR", 2, DirectX), # 0x76
    InstrDesc("???", 1, Illegal), # 0x77
    InstrDesc("SEI", 1, Implicit), # 0x78
    InstrDesc("ADC", 3, AbsoluteY), # 0x79
    InstrDesc("???", 1, Illegal), # 0x7a
    InstrDesc("???", 1, Illegal), # 0x7b
    InstrDesc("???", 1, Illegal), # 0x7c
    InstrDesc("ADC", 3, AbsoluteX), # 0x7d
    InstrDesc("ROR", 3, AbsoluteX), # 0x7e
    InstrDesc("???", 1, Illegal), # 0x7f
    InstrDesc("???", 1, Illegal), # 0x80
    InstrDesc("STA", 2, DirectXIndirect), # 0x81
    InstrDesc("???", 1, Illegal), # 0x82
    InstrDesc("???", 1, Illegal), # 0x83
    InstrDesc("STY", 2, Direct), # 0x84
    InstrDesc("STA", 2, Direct), # 0x85
    InstrDesc("STX", 2, Direct), # 0x86
    InstrDesc("???", 1, Illegal), # 0x87
    InstrDesc("DEY", 1, Implicit), # 0x88
    InstrDesc("???", 1, Illegal), # 0x89
    InstrDesc("TXA", 1, Implicit), # 0x8a
    InstrDesc("???", 1, Illegal), # 0x8b
    InstrDesc("STY", 3, Absolute), # 0x8c
    InstrDesc("STA", 3, Absolute), # 0x8d
    InstrDesc("STX", 3, Absolute), # 0x8e
    InstrDesc("???", 1, Illegal), # 0x8f
    InstrDesc("BCC", 2, Relative), # 0x90
    InstrDesc("STA", 2, DirectIndirectY), # 0x91
    InstrDesc("???", 1, Illegal), # 0x92
    InstrDesc("???", 1, Illegal), # 0x93
    InstrDesc("STY", 2, DirectX), # 0x94
    InstrDesc("STA", 2, DirectX), # 0x95
    InstrDesc("STX", 2, DirectY), # 0x96
    InstrDesc("???", 1, Illegal), # 0x97
    InstrDesc("TYA", 1, Implicit), # 0x98
    InstrDesc("STA", 3, AbsoluteY), # 0x99
    InstrDesc("TXS", 1, Implicit), # 0x9a
    InstrDesc("???", 1, Illegal), # 0x9b
    InstrDesc("???", 1, Illegal), # 0x9c
    InstrDesc("STA", 3, AbsoluteX), # 0x9d
    InstrDesc("???", 1, Illegal), # 0x9e
    InstrDesc("???", 1, Illegal), # 0x9f
    InstrDesc("LDY", 2, Immediate), # 0xa0
    InstrDesc("LDA", 2, DirectXIndirect), # 0xa1
    InstrDesc("LDX", 2, Immediate), # 0xa2
    InstrDesc("???", 1, Illegal), # 0xa3
    InstrDesc("LDY", 2, Direct), # 0xa4
    InstrDesc("LDA", 2, Direct), # 0xa5
    InstrDesc("LDX", 2, Direct), # 0xa6
    InstrDesc("???", 1, Illegal), # 0xa7
    InstrDesc("TAY", 1, Implicit), # 0xa8
    InstrDesc("LDA", 2, Immediate), # 0xa9
    InstrDesc("TAX", 1, Implicit), # 0xaa
    InstrDesc("???", 1, Illegal), # 0xab
    InstrDesc("LDY", 3, Absolute), # 0xac
    InstrDesc("LDA", 3, Absolute), # 0xad
    InstrDesc("LDX", 3, Absolute), # 0xae
    InstrDesc("???", 1, Illegal), # 0xaf
    InstrDesc("BCS", 2, Relative), # 0xb0
    InstrDesc("LDA", 2, DirectIndirectY), # 0xb1
    InstrDesc("???", 1, Illegal), # 0xb2
    InstrDesc("???", 1, Illegal), # 0xb3
    InstrDesc("LDY", 2, DirectX), # 0xb4
    InstrDesc("LDA", 2, DirectX), # 0xb5
    InstrDesc("LDX", 2, DirectY), # 0xb6
    InstrDesc("???", 1, Illegal), # 0xb7
    InstrDesc("CLV", 1, Implicit), # 0xb8
    InstrDesc("LDA", 3, AbsoluteY), # 0xb9
    InstrDesc("TSX", 1, Implicit), # 0xba
    InstrDesc("???", 1, Illegal), # 0xbb
    InstrDesc("LDY", 3, AbsoluteX), # 0xbc
    InstrDesc("LDA", 3, AbsoluteX), # 0xbd
    InstrDesc("LDX", 3, AbsoluteY), # 0xbe
    InstrDesc("???", 1, Illegal), # 0xbf
    InstrDesc("CPY", 2, Immediate), # 0xc0
    InstrDesc("CMP", 2, DirectXIndirect), # 0xc1
    InstrDesc("???", 1, Illegal), # 0xc2
    InstrDesc("???", 1, Illegal), # 0xc3
    InstrDesc("CPY", 2, Direct), # 0xc4
    InstrDesc("CMP", 2, Direct), # 0xc5
    InstrDesc("DEC", 2, Direct), # 0xc6
    InstrDesc("???", 1, Illegal), # 0xc7
    InstrDesc("INY", 1, Implicit), # 0xc8
    InstrDesc("CMP", 2, Immediate), # 0xc9
    InstrDesc("DEX", 1, Implicit), # 0xca
    InstrDesc("???", 1, Illegal), # 0xcb
    InstrDesc("CPY", 3, Absolute), # 0xcc
    InstrDesc("CMP", 3, Absolute), # 0xcd
    InstrDesc("DEC", 3, Absolute), # 0xce
    InstrDesc("???", 1, Illegal), # 0xcf
    InstrDesc("BNE", 2, Relative), # 0xd0
    InstrDesc("CMP", 2, DirectIndirectY), # 0xd1
    InstrDesc("???", 1, Illegal), # 0xd2
    InstrDesc("???", 1, Illegal), # 0xd3
    InstrDesc("???", 1, Illegal), # 0xd4
    InstrDesc("CMP", 2, DirectX), # 0xd5
    InstrDesc("DEC", 2, DirectX), # 0xd6
    InstrDesc("???", 1, Illegal), # 0xd7
    InstrDesc("CLD", 1, Implicit), # 0xd8
    InstrDesc("CMP", 3, AbsoluteY), # 0xd9
    InstrDesc("???", 1, Illegal), # 0xda
    InstrDesc("???", 1, Illegal), # 0xdb
    InstrDesc("???", 1, Illegal), # 0xdc
    InstrDesc("CMP", 3, AbsoluteX), # 0xdd
    InstrDesc("DEC", 3, AbsoluteX), # 0xde
    InstrDesc("???", 1, Illegal), # 0xdf
    InstrDesc("CPX", 2, Immediate), # 0xe0
    InstrDesc("SBC", 2, DirectXIndirect), # 0xe1
    InstrDesc("???", 1, Illegal), # 0xe2
    InstrDesc("???", 1, Illegal), # 0xe3
    InstrDesc("CPX", 2, Direct), # 0xe4
    InstrDesc("SBC", 2, Direct), # 0xe5
    InstrDesc("INC", 2, Direct), # 0xe6
    InstrDesc("???", 1, Illegal), # 0xe7
    InstrDesc("INX", 1, Implicit), # 0xe8
    InstrDesc("SBC", 2, Immediate), # 0xe9
    InstrDesc("NOP", 1, Implicit), # 0xea
    InstrDesc("???", 1, Illegal), # 0xeb
    InstrDesc("CPX", 3, Absolute), # 0xec
    InstrDesc("SBC", 3, Absolute), # 0xed
    InstrDesc("INC", 3, Absolute), # 0xee
    InstrDesc("???", 1, Illegal), # 0xef
    InstrDesc("BEQ", 2, Relative), # 0xf0
    InstrDesc("SBC", 2, DirectIndirectY), # 0xf1
    InstrDesc("???", 1, Illegal), # 0xf2
    InstrDesc("???", 1, Illegal), # 0xf3
    InstrDesc("???", 1, Illegal), # 0xf4
    InstrDesc("SBC", 2, DirectX), # 0xf5
    InstrDesc("INC", 2, DirectX), # 0xf6
    InstrDesc("???", 1, Illegal), # 0xf7
    InstrDesc("SED", 1, Implicit), # 0xf8
    InstrDesc("SBC", 3, AbsoluteY), # 0xf9
    InstrDesc("???", 1, Illegal), # 0xfa
    InstrDesc("???", 1, Illegal), # 0xfb
    InstrDesc("???", 1, Illegal), # 0xfc
    InstrDesc("SBC", 3, AbsoluteX), # 0xfd
    InstrDesc("INC", 3, AbsoluteX), # 0xfe
    InstrDesc("???", 1, Illegal) # 0xff
]
